---
services:
  redis-master:
    extends:
      file: ./docker-compose.includes.yaml
      service: redis-base
    container_name: redis-master
    volumes:
      - ./data/master:/data
    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --port
      - "6379"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --protected-mode
      - "no"
      - --replica-announce-ip
      - ${HOST_ENV_IP:-${MASTER_IP}}
      - --replica-announce-port
      - ${MASTER_PORT}
    ports:
      - "${MASTER_PORT:-20001}:6379"

  sentinel-first:
    extends:
      file: ./docker-compose.includes.yaml
      service: sentinel-base
    container_name: sentinel-first
    ports:
      - "${SENTINEL_FIRST_PORT:-30001}:26379"


  sentinel-third:
    extends:
      file: ./docker-compose.includes.yaml
      service: sentinel-base
    container_name: sentinel-third
    ports:
      - "${SENTINEL_THIRD_PORT:-30003}:26379"
